version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: mongoose_app
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/mongoose-typescript-app
      - PIXABAY_API_KEY=45640711-3b2c9c3e0dd9ac6e6a5b798be
    volumes:
      - .:/app

volumes:
  mongo_data:
